name: 'Test Fivetran integration'
on:
  push:
    branches:
      - main
  schedule:
    - cron: '00 12 * * *'
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Gel CLI and nightly server (Linux)
        run: |
          bash <(curl --proto '=https' --tlsv1.2 -sSf https://sh.edgedb.com) -y
          gel server install --nightly
          ln -s `gel server info --channel=nightly --get bin-path` ~/.local/bin/edgedb-server
          ln -s `gel server info --channel=nightly --get bin-path` ~/.local/bin/gel-server

      - name: Cache build
        id: cache-build
        uses: actions/cache@v4
        with:
          path: target/debug/runner
          key: ${{ runner.os }}-${{ hashFiles('**/*.{rs,toml,gel,edgeql}') }}

      - name: Install Rust toolchain
        if: steps.cache-build.outputs.cache-hit != 'true'
        uses: dtolnay/rust-toolchain@stable
      - name: Build
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: cargo build --locked

      - name: Run
        env:
          RUST_LOG: runner=debug,
          FIVETRAN_AUTHORIZATION: ${{ secrets.FIVETRAN_AUTHORIZATION }}
          BORE_SERVER_IP: ${{ secrets.BORE_SERVER_IP }}
          BORE_SERVER_SECRET: ${{ secrets.BORE_SERVER_SECRET }}
        run: ./target/debug/runner
